// ============================================================
//  FACIT (det riktiga utfallet) – fyll på i denna fil direkt på GitHub.
//
//  matches: lägg till en rad när en match spelats, t.ex.  A1: { score: "2-0" }
//  groups:  slutlig tabell per grupp, t.ex.  A: ["1:a","2:a","3:a","4:a"]
//  special: winner = mästaren, top4 = ALLA 4 i topp 4 (mästare + 2:a/3:a/4:a),
//           goldenBoot, mostAssists, mostGoalsCountry, bestKeeper, firstGoal.
//           Skriv exakt samma stavning som spelarna använt.

// ============================================================

const FACIT = {
  matches: {
    A1: { score: "2-0" },
    A2: { score: "2-1" },
    B1: { score: "1-1" },
    C1: { score: "4-1" },
    B2: { score: "1-1" },
    D1: { score: "1-1" },
    D2: { score: "0-1" },
    C2: { score: "2-0" },
    E1: { score: "7-1" },
    F1: { score: "2-2" },
    E2: { score: "1-0" },
    F2: { score: "5-1" },
    G1: { score: "0-0" },
    H1: { score: "1-1" },
    G2: { score: "1-1" },
    H2: { score: "2-2" },
    I1: { score: "3-1" },
    I2: { score: "1-4" },
    J1: { score: "3-0" },
    J2: { score: "3-1" },
    K1: { score: "1-1" },
    L1: { score: "4-2" },
    L2: { score: "1-0" },
    K2: { score: "1-3" },
    A3: { score: "1-1" },
    B3: { score: "4-1" },
    B4: { score: "6-0" },
    A4: { score: "1-0" },
    C3: { score: "2-0" },
    D3: { score: "0-1" },
    D4: { score: "3-0" },
    C4: { score: "0-1" },
    F3: { score: "5-1" },
    E3: { score: "2-1" },
    E4: { score: "0-0" },
    F4: { score: "0-4" },
    G3: { score: "4-0" },
    H3: { score: "0-0" },
    G4: { score: "2-2" },
    H4: { score: "1-3" },
    J3: { score: "2-0" },
    I3: { score: "3-0" },
    I4: { score: "3-2" },
    J4: { score: "1-2" },
    K3: { score: "5-0" },
    L3: { score: "0-0" },
    L4: { score: "0-1" },
    K4: { score: "1-0" },
    B5: { score: "2-1" },
    B6: { score: "3-1" },
    D5: { score: "4-2" },
    D6: { score: "0-3" },
    A5: { score: "1-0" },
    A6: { score: "0-3" },
    E5: { score: "0-2" },
    E6: { score: "2-1" },
    F5: { score: "1-3" },
    F6: { score: "1-1" },
    C5: { score: "3-2" },
    C6: { score: "0-0" },
    I5: { score: "1-4" },
    I6: { score: "5-0" },
    G5: { score: "0-0" },
    G6: { score: "0-1" },
    H5: { score: "1-5" },
    H6: { score: "1-1" },
  },
  groups: {
    A: [ "Mexiko", "Sydafrika", "Sydkorea", "Tjeckien" ],
    B: [ "Schweiz", "Kanada", "Bosnien&Her", "Qatar" ],
    C: [ "USA", "Australien", "Paraguay", "Turkiet" ],
    D: [ "Brasilien", "Marocko", "Skottland", "Haiti" ],
    E: [ "Tyskland", "Elfenbenskusten", "Ecuador", "Curaçao" ],
    F: [ "Nederländerna", "Japan", "Sverige", "Tunisien" ],

  },
  special: {
    firstGoal: "Mexico",
  },
};
