// ============================================================
//  SPELARE OCH DERAS TIPS  (genererat exakt ur kalkylarket)
//
//  matches: { "A1": { score: "2-1" } }                 1X2 härleds ur resultatet
//           { "A1": { outcome: "X" } }                  bara 1X2 ifyllt
//           { "A1": { outcome: "1", score: "1-3" } }    1X2-valet styr 10-poängen
//  groups:  { A: ["1:a","2:a","3:a","4:a"], ... }
//  special: { winner, top4:[3 lag], goldenBoot, mostAssists, mostGoalsCountry, bestKeeper, firstGoal }
// ============================================================

const PLAYERS = [
  {
    id: "backis",
    name: "Bäckis ☆",
    avatar: "👑",
    special: {
      winner: "Spanien",
      top4: ["England", "Frankrike", "Tyskland"],
      goldenBoot: "Erling Haaland",
      mostAssists: "Bruno Fernandes",
      mostGoalsCountry: "Spanien",
      bestKeeper: "Alisson",
      firstGoal: "Mexico",
    },
    matches: {
      A1: { score: "3-1" }, A2: { score: "1-0" }, A3: { score: "2-1" },
      A4: { score: "1-0" }, A5: { score: "0-1" }, A6: { score: "1-2" },
      B1: { score: "0-3" }, B2: { score: "1-3" }, B3: { score: "2-2" },
      B4: { score: "0-0" }, B5: { score: "2-1" }, B6: { score: "1-0" },
      C1: { score: "1-1" }, C2: { score: "0-1" }, C3: { score: "0-0" },
      C4: { score: "2-1" }, C5: { score: "1-0" }, C6: { score: "1-0" },
      D1: { score: "2-1" }, D2: { score: "1-1" }, D3: { score: "0-1" },
      D4: { score: "3-0" }, D5: { score: "0-0" }, D6: { score: "0-2" },
      E1: { score: "4-1" }, E2: { score: "0-0" }, E3: { score: "2-0" },
      E4: { score: "1-1" }, E5: { score: "1-1" }, E6: { score: "0-2" },
      F1: { score: "2-1" }, F2: { score: "1-0" }, F3: { score: "2-1" },
      F4: { score: "0-0" }, F5: { score: "1-3" }, F6: { score: "0-1" },
      G1: { score: "3-0" }, G2: { score: "0-2" }, G3: { score: "3-0" },
      G4: { score: "2-0" }, G5: { score: "1-0" }, G6: { score: "1-2" },
      H1: { score: "2-0" }, H2: { score: "0-0" }, H3: { score: "2-1" },
      H4: { score: "0-0" }, H5: { score: "0-1" }, H6: { score: "0-0" },
      I1: { score: "4-0" }, I2: { score: "1-2" }, I3: { score: "3-0" },
      I4: { score: "1-0" }, I5: { score: "1-3" }, I6: { score: "1-1" },
      J1: { score: "2-1" }, J2: { score: "1-0" }, J3: { score: "2-1" },
      J4: { score: "0-1" }, J5: { score: "1-0" }, J6: { score: "0-2" },
      K1: { score: "2-0" }, K2: { score: "0-2" }, K3: { score: "2-0" },
      K4: { score: "1-0" }, K5: { score: "0-1" }, K6: { score: "0-0" },
      L1: { score: "1-1" }, L2: { score: "1-0" }, L3: { score: "3-1" },
      L4: { score: "1-3" }, L5: { score: "0-3" }, L6: { score: "2-1" },
    },
    groups: {
      A: ["Mexiko", "Sydkorea", "Tjeckien", "Sydafrika"],
      B: ["Schweiz", "Bosnien&Her", "Qatar", "Kanada"],
      C: ["Turkiet", "Paraguay", "Australien", "USA"],
      D: ["Brasilien", "Marocko", "Skottland", "Haiti"],
      E: ["Tyskland", "Ecuador", "Curaçao", "Elfenbenskusten"],
      F: ["Nederländerna", "Tunisien", "Sverige", "Japan"],
      G: ["Spanien", "Uruguay", "Saudiarabien", "Kap Verde"],
      H: ["Belgien", "Iran", "Egypten", "Nya Zeeland"],
      I: ["Frankrike", "Senegal", "Norge", "Irak"],
      J: ["Argentina", "Algeriet", "Österrike", "Jordanien"],
      K: ["Portugal", "Colombia", "Uzbekistan", "DR Kongo"],
      L: ["England", "Kroatien", "Panama", "Ghana"],
    },
  },
  {
    id: "simpa",
    name: "Simpa",
    avatar: "🦊",
    special: {
      winner: "Portugal",
      top4: ["Frankrike", "Spanien", "England"],
      goldenBoot: "Kylian Mbappe",
      mostAssists: "Lamine Yamal",
      mostGoalsCountry: "Spanien",
      bestKeeper: "Diogo Costa",
      firstGoal: "Mexico",
    },
    matches: {
      A1: { score: "2-0" }, A2: { score: "1-1" }, A3: { score: "2-2" },
      A4: { score: "2-1" }, A5: { score: "0-2" }, A6: { score: "0-1" },
      B1: { score: "2-1" }, B2: { score: "0-2" }, B3: { score: "2-1" },
      B4: { score: "3-1" }, B5: { score: "2-3" }, B6: { score: "3-1" },
      C1: { score: "2-1" }, C2: { score: "0-3" }, C3: { score: "2-2" },
      C4: { score: "2-1" }, C5: { score: "2-1" }, C6: { score: "1-0" },
      D1: { score: "3-1" }, D2: { score: "1-2" }, D3: { score: "0-2" },
      D4: { score: "3-1" }, D5: { score: "3-1" }, D6: { score: "1-2" },
      E1: { score: "2-0" }, E2: { score: "3-3" }, E3: { score: "3-1" },
      E4: { score: "1-1" }, E5: { score: "0-1" }, E6: { score: "2-3" },
      F1: { score: "3-1" }, F2: { score: "3-1" }, F3: { score: "2-1" },
      F4: { score: "0-1" }, F5: { score: "0-3" }, F6: { score: "1-2" },
      G1: { score: "4-1" }, G2: { score: "1-2" }, G3: { score: "4-0" },
      G4: { score: "3-1" }, G5: { score: "1-1" }, G6: { score: "1-3" },
      H1: { score: "2-1" }, H2: { score: "1-0" }, H3: { score: "4-1" },
      H4: { score: "1-2" }, H5: { score: "1-2" }, H6: { score: "2-1" },
      I1: { score: "3-1" }, I2: { score: "0-2" }, I3: { score: "4-0" },
      I4: { score: "1-1" }, I5: { score: "1-3" }, I6: { score: "2-1" },
      J1: { score: "2-0" }, J2: { score: "2-1" }, J3: { score: "2-0" },
      J4: { score: "0-0" }, J5: { score: "0-2" }, J6: { score: "1-3" },
      K1: { score: "3-0" }, K2: { score: "0-1" }, K3: { score: "2-0" },
      K4: { score: "2-1" }, K5: { score: "2-3" }, K6: { score: "1-1" },
      L1: { score: "4-2" }, L2: { score: "1-1" }, L3: { score: "3-0" },
      L4: { score: "0-1" }, L5: { score: "0-3" }, L6: { score: "3-1" },
    },
    groups: {
      A: ["Mexiko", "Sydkorea", "Tjeckien", "Sydafrika"],
      B: ["Schweiz", "Kanada", "Bosnien&Her", "Qatar"],
      C: ["USA", "Turkiet", "Paraguay", "Australien"],
      D: ["Brasilien", "Marocko", "Skottland", "Haiti"],
      E: ["Tyskland", "Ecuador", "Elfenbenskusten", "Curaçao"],
      F: ["Nederländerna", "Sverige", "Japan", "Tunisien"],
      G: ["Spanien", "Uruguay", "Saudiarabien", "Kap Verde"],
      H: ["Belgien", "Iran", "Egypten", "Nya Zeeland"],
      I: ["Frankrike", "Norge", "Senegal", "Irak"],
      J: ["Argentina", "Österrike", "Algeriet", "Jordanien"],
      K: ["Portugal", "Colombia", "Uzbekistan", "DR Kongo"],
      L: ["England", "Kroatien", "Ghana", "Panama"],
    },
  },
  {
    id: "wasse",
    name: "Wasse",
    avatar: "🐺",
    special: {
      winner: "Frankrike",
      top4: ["England", "Spanien", "Argentina"],
      goldenBoot: "Kylian Mbappe",
      mostAssists: "Lamine Yamal",
      mostGoalsCountry: "Frankrike",
      bestKeeper: "Mike Maignan",
      firstGoal: "Mexico",
    },
    matches: {
      A1: { score: "2-1" }, A2: { score: "1-2" }, A3: { score: "2-2" },
      A4: { score: "1-1" }, A5: { score: "0-1" }, A6: { score: "1-2" },
      B1: { score: "3-1" }, B2: { score: "0-2" }, B3: { score: "3-2" },
      B4: { score: "2-0" }, B5: { score: "2-1" }, B6: { score: "2-1" },
      C1: { score: "1-1" }, C2: { score: "1-2" }, C3: { score: "2-1" },
      C4: { score: "2-1" }, C5: { score: "1-2" }, C6: { score: "2-2" },
      D1: { score: "3-1" }, D2: { score: "0-2" }, D3: { score: "1-2" },
      D4: { score: "4-0" }, D5: { score: "2-0" }, D6: { score: "1-3" },
      E1: { score: "4-1" }, E2: { score: "2-2" }, E3: { score: "3-1" },
      E4: { score: "2-0" }, E5: { score: "1-2" }, E6: { score: "1-2" },
      F1: { score: "2-1" }, F2: { score: "3-1" }, F3: { score: "2-2" },
      F4: { score: "1-3" }, F5: { score: "1-3" }, F6: { score: "2-3" },
      G1: { score: "3-0" }, G2: { score: "1-3" }, G3: { score: "3-0" },
      G4: { score: "3-1" }, G5: { score: "2-2" }, G6: { score: "1-2" },
      H1: { score: "2-1" }, H2: { score: "1-1" }, H3: { score: "3-1" },
      H4: { score: "1-1" }, H5: { score: "1-2" }, H6: { score: "2-1" },
      I1: { score: "3-1" }, I2: { score: "1-2" }, I3: { score: "3-1" },
      I4: { score: "2-1" }, I5: { score: "1-2" }, I6: { score: "2-1" },
      J1: { score: "4-1" }, J2: { score: "2-0" }, J3: { score: "2-1" },
      J4: { score: "2-2" }, J5: { score: "1-2" }, J6: { score: "0-3" },
      K1: { score: "3-1" }, K2: { score: "1-3" }, K3: { score: "3-0" },
      K4: { score: "2-1" }, K5: { score: "2-3" }, K6: { score: "2-2" },
      L1: { score: "2-1" }, L2: { score: "3-2" }, L3: { score: "3-1" },
      L4: { score: "1-2" }, L5: { score: "0-3" }, L6: { score: "2-1" },
    },
    groups: {
      A: ["Sydkorea", "Mexiko", "Tjeckien", "Sydafrika"],
      B: ["Schweiz", "Kanada", "Bosnien&Her", "Qatar"],
      C: ["USA", "Turkiet", "Paraguay", "Australien"],
      D: ["Brasilien", "Marocko", "Skottland", "Haiti"],
      E: ["Tyskland", "Ecuador", "Elfenbenskusten", "Curaçao"],
      F: ["Nederländerna", "Sverige", "Japan", "Tunisien"],
      G: ["Spanien", "Uruguay", "Saudiarabien", "Kap Verde"],
      H: ["Belgien", "Egypten", "Iran", "Nya Zeeland"],
      I: ["Frankrike", "Norge", "Senegal", "Irak"],
      J: ["Argentina", "Österrike", "Algeriet", "Jordanien"],
      K: ["Portugal", "Colombia", "DR Kongo", "Uzbekistan"],
      L: ["England", "Kroatien", "Ghana", "Panama"],
    },
  },
  {
    id: "calle-l",
    name: "Calle L",
    avatar: "🦁",
    special: {
      winner: "Brasilien",
      top4: ["Frankrike", "Portugal", "Spanien"],
      goldenBoot: "Vinicius Jr",
      mostAssists: "Michael Olise",
      mostGoalsCountry: "Brasilien",
      bestKeeper: "Alisson",
      firstGoal: "Sydafrika",
    },
    matches: {
      A1: { score: "1-1" }, A2: { score: "2-1" }, A3: { score: "2-0" },
      A4: { score: "1-1" }, A5: { score: "0-3" }, A6: { score: "1-2" },
      B1: { score: "0-2" }, B2: { score: "0-2" }, B3: { score: "3-1" },
      B4: { score: "2-1" }, B5: { score: "2-0" }, B6: { score: "2-0" },
      C1: { score: "2-1" }, C2: { score: "1-3" }, C3: { score: "2-0" },
      C4: { score: "2-0" }, C5: { score: "2-2" }, C6: { score: "1-1" },
      D1: { score: "4-2" }, D2: { score: "0-1" }, D3: { score: "0-2" },
      D4: { score: "6-0" }, D5: { score: "3-0" }, D6: { score: "1-4" },
      E1: { score: "3-0" }, E2: { score: "0-0" }, E3: { score: "2-2" },
      E4: { score: "2-0" }, E5: { score: "0-3" }, E6: { score: "1-1" },
      F1: { score: "1-3" }, F2: { score: "2-0" }, F3: { score: "2-0" },
      F4: { score: "0-3" }, F5: { score: "0-4" }, F6: { score: "1-1" },
      G1: { score: "3-0" }, G2: { score: "0-2" }, G3: { score: "3-0" },
      G4: { score: "2-0" }, G5: { score: "1-0" }, G6: { score: "0-2" },
      H1: { score: "3-0" }, H2: { score: "2-1" }, H3: { score: "3-0" },
      H4: { score: "1-3" }, H5: { score: "1-5" }, H6: { score: "0-0" },
      I1: { score: "2-0" }, I2: { score: "1-1" }, I3: { score: "3-0" },
      I4: { score: "1-3" }, I5: { score: "1-4" }, I6: { score: "2-1" },
      J1: { score: "2-0" }, J2: { score: "2-1" }, J3: { score: "2-1" },
      J4: { score: "1-2" }, J5: { score: "0-1" }, J6: { score: "0-3" },
      K1: { score: "2-0" }, K2: { score: "1-2" }, K3: { score: "4-0" },
      K4: { score: "2-1" }, K5: { score: "1-2" }, K6: { score: "2-1" },
      L1: { score: "1-1" }, L2: { score: "2-0" }, L3: { score: "1-1" },
      L4: { score: "0-2" }, L5: { score: "0-3" }, L6: { score: "2-3" },
    },
    groups: {
      A: ["Sydkorea", "Mexiko", "Tjeckien", "Sydafrika"],
      B: ["Schweiz", "Bosnien&Her", "Kanada", "Qatar"],
      C: ["Turkiet", "USA", "Paraguay", "Australien"],
      D: ["Brasilien", "Marocko", "Skottland", "Haiti"],
      E: ["Tyskland", "Elfenbenskusten", "Ecuador", "Curaçao"],
      F: ["Japan", "Nederländerna", "Sverige", "Tunisien"],
      G: ["Spanien", "Uruguay", "Kap Verde", "Saudiarabien"],
      H: ["Belgien", "Iran", "Egypten", "Nya Zeeland"],
      I: ["Frankrike", "Senegal", "Irak", "Norge"],
      J: ["Argentina", "Österrike", "Algeriet", "Jordanien"],
      K: ["Portugal", "Colombia", "DR Kongo", "Uzbekistan"],
      L: ["Ghana", "England", "Kroatien", "Panama"],
    },
  },
  {
    id: "oliver",
    name: "Oliver",
    avatar: "🦅",
    special: {
      winner: "Spanien",
      top4: ["Frankrike", "Argentina", "Brasilien"],
      goldenBoot: "Kylian Mbappe",
      mostAssists: "Lamine Yamal",
      mostGoalsCountry: "Spanien",
      bestKeeper: "Joan Garcia",
      firstGoal: "Mexico",
    },
    matches: {
      A1: { score: "1-0" }, A2: { score: "2-1" }, A3: { score: "2-1" },
      A4: { score: "0-1" }, A5: { score: "0-2" }, A6: { score: "1-1" },
      B1: { score: "1-1" }, B2: { score: "1-3" }, B3: { score: "2-0" },
      B4: { score: "1-1" }, B5: { score: "1-0" }, B6: { score: "2-0" },
      C1: { score: "2-0" }, C2: { score: "0-2" }, C3: { score: "2-0" },
      C4: { score: "2-0" }, C5: { score: "2-1" }, C6: { score: "1-0" },
      D1: { score: "3-1" }, D2: { score: "0-2" }, D3: { score: "1-2" },
      D4: { score: "6-0" }, D5: { score: "2-0" }, D6: { score: "1-3" },
      E1: { score: "6-0" }, E2: { score: "0-1" }, E3: { score: "3-0" },
      E4: { score: "2-0" }, E5: { score: "0-1" }, E6: { score: "0-3" },
      F1: { score: "2-0" }, F2: { score: "2-1" }, F3: { score: "1-1" },
      F4: { score: "0-2" }, F5: { score: "0-3" }, F6: { score: "1-2" },
      G1: { score: "4-0" }, G2: { score: "1-3" }, G3: { score: "4-0" },
      G4: { score: "2-0" }, G5: { score: "0-1" }, G6: { score: "1-3" },
      H1: { score: "2-0" }, H2: { score: "1-1" }, H3: { score: "3-1" },
      H4: { score: "0-2" }, H5: { score: "0-3" }, H6: { score: "2-1" },
      I1: { score: "3-1" }, I2: { score: "0-3" }, I3: { score: "3-0" },
      I4: { score: "2-1" }, I5: { score: "1-3" }, I6: { score: "1-0" },
      J1: { score: "3-0" }, J2: { score: "1-0" }, J3: { score: "3-1" },
      J4: { score: "0-0" }, J5: { score: "0-1" }, J6: { score: "0-4" },
      K1: { score: "2-0" }, K2: { score: "0-2" }, K3: { score: "2-0" },
      K4: { score: "1-0" }, K5: { score: "1-2" }, K6: { score: "0-0" },
      L1: { score: "2-1" }, L2: { score: "0-0" }, L3: { score: "3-0" },
      L4: { score: "0-2" }, L5: { score: "0-3" }, L6: { score: "2-0" },
    },
    groups: {
      A: ["Sydkorea", "Tjeckien", "Mexiko", "Sydafrika"],
      B: ["Schweiz", "Kanada", "Bosnien&Her", "Qatar"],
      C: ["Turkiet", "USA", "Paraguay", "Australien"],
      D: ["Brasilien", "Marocko", "Skottland", "Haiti"],
      E: ["Tyskland", "Ecuador", "Elfenbenskusten", "Curaçao"],
      F: ["Sverige", "Nederländerna", "Japan", "Tunisien"],
      G: ["Spanien", "Uruguay", "Saudiarabien", "Kap Verde"],
      H: ["Belgien", "Egypten", "Iran", "Nya Zeeland"],
      I: ["Frankrike", "Norge", "Senegal", "Irak"],
      J: ["Argentina", "Österrike", "Jordanien", "Algeriet"],
      K: ["Portugal", "Colombia", "DR Kongo", "Uzbekistan"],
      L: ["England", "Kroatien", "Panama", "Ghana"],
    },
  },
  {
    id: "hagge",
    name: "Hagge",
    avatar: "🐻",
    special: {
      winner: "Portugal",
      top4: ["Spanien", "Frankrike", "England"],
      goldenBoot: "Harry Kane",
      mostAssists: "Bruno Fernandes",
      mostGoalsCountry: "Brasilien",
      bestKeeper: "Alisson",
      firstGoal: "Mexico",
    },
    matches: {
      A1: { score: "2-0" }, A2: { score: "1-1" }, A3: { score: "2-0" },
      A4: { score: "2-1" }, A5: { score: "0-1" }, A6: { score: "1-1" },
      B1: { score: "1-1" }, B2: { score: "0-3" }, B3: { score: "3-1" },
      B4: { score: "2-0" }, B5: { score: "2-0" }, B6: { score: "2-1" },
      C1: { score: "2-1" }, C2: { score: "1-2" }, C3: { score: "2-2" },
      C4: { score: "1-1" }, C5: { score: "1-1" }, C6: { score: "1-0" },
      D1: { score: "2-1" }, D2: { score: "0-2" }, D3: { score: "0-2" },
      D4: { score: "4-0" }, D5: { score: "4-1" }, D6: { score: "1-3" },
      E1: { score: "5-0" }, E2: { score: "1-2" }, E3: { score: "3-1" },
      E4: { score: "3-0" }, E5: { score: "0-2" }, E6: { score: "1-2" },
      F1: { score: "1-0" }, F2: { score: "1-0" }, F3: { score: "2-0" },
      F4: { score: "0-2" }, F5: { score: "0-3" }, F6: { score: "1-1" },
      G1: { score: "6-0" }, G2: { score: "0-1" }, G3: { score: "3-0" },
      G4: { score: "2-0" }, G5: { score: "0-0" }, G6: { score: "0-1" },
      H1: { score: "3-1" }, H2: { score: "0-0" }, H3: { score: "4-0" },
      H4: { score: "1-1" }, H5: { outcome: "2" }, H6: { outcome: "1" },
      I1: { score: "3-1" }, I2: { score: "1-3" }, I3: { score: "4-1" },
      I4: { score: "2-2" }, I5: { score: "1-3" }, I6: { score: "2-0" },
      J1: { score: "2-0" }, J2: { score: "2-0" }, J3: { score: "1-2" },
      J4: { score: "0-1" }, J5: { score: "1-2" }, J6: { score: "0-2" },
      K1: { score: "4-0" }, K2: { score: "0-3" }, K3: { score: "2-0" },
      K4: { score: "3-0" }, K5: { score: "1-2" }, K6: { score: "0-0" },
      L1: { score: "1-1" }, L2: { score: "2-1" }, L3: { score: "3-1" },
      L4: { score: "0-2" }, L5: { score: "0-3" }, L6: { score: "2-0" },
    },
    groups: {
      A: ["Mexiko", "Tjeckien", "Sydkorea", "Sydafrika"],
      B: ["Schweiz", "Bosnien&Her", "Kanada", "Qatar"],
      C: ["Turkiet", "USA", "Paraguay", "Australien"],
      D: ["Brasilien", "Marocko", "Skottland", "Haiti"],
      E: ["Tyskland", "Ecuador", "Elfenbenskusten", "Curaçao"],
      F: ["Nederländerna", "Japan", "Sverige", "Tunisien"],
      G: ["Spanien", "Uruguay", "Saudiarabien", "Kap Verde"],
      H: ["Belgien", "Egypten", "Nya Zeeland", "Iran"],
      I: ["Frankrike", "Norge", "Senegal", "Irak"],
      J: ["Argentina", "Österrike", "Algeriet", "Jordanien"],
      K: ["Portugal", "Colombia", "DR Kongo", "Uzbekistan"],
      L: ["England", "Kroatien", "Ghana", "Panama"],
    },
  },
  {
    id: "calle-j",
    name: "Calle J",
    avatar: "🐉",
    special: {
      winner: "Spanien",
      top4: ["Frankrike", "Argentina", "England"],
      goldenBoot: "Kylian Mbappe",
      mostAssists: "Lamine Yamal",
      mostGoalsCountry: "Spanien",
      bestKeeper: "Unai Simón",
      firstGoal: "Mexico",
    },
    matches: {
      A1: { score: "2-1" }, A2: { score: "1-1" }, A3: { score: "1-0" },
      A4: { score: "1-2" }, A5: { score: "0-1" }, A6: { score: "0-1" },
      B1: { score: "2-0" }, B2: { score: "0-3" }, B3: { score: "1-1" },
      B4: { score: "2-0" }, B5: { score: "2-1" }, B6: { score: "1-0" },
      C1: { score: "3-1" }, C2: { score: "2-2" }, C3: { score: "3-1" },
      C4: { score: "0-0" }, C5: { score: "0-1" }, C6: { score: "1-2" },
      D1: { score: "3-1" }, D2: { score: "0-2" }, D3: { score: "2-2" },
      D4: { score: "3-0" }, D5: { score: "3-0" }, D6: { score: "1-2" },
      E1: { score: "2-0" }, E2: { score: "1-2" }, E3: { score: "3-0" },
      E4: { score: "1-0" }, E5: { score: "0-1" }, E6: { score: "0-2" },
      F1: { score: "2-0" }, F2: { score: "2-1" }, F3: { score: "2-1" },
      F4: { score: "2-1" }, F5: { score: "2-1" }, F6: { score: "2-3" },
      G1: { score: "3-0" }, G2: { score: "0-2" }, G3: { score: "4-0" },
      G4: { score: "2-1" }, G5: { score: "0-0" }, G6: { score: "1-3" },
      H1: { score: "1-0" }, H2: { score: "3-2" }, H3: { score: "2-0" },
      H4: { score: "1-2" }, H5: { score: "0-1" }, H6: { score: "1-0" },
      I1: { score: "3-1" }, I2: { score: "0-1" }, I3: { score: "2-0" },
      I4: { score: "1-0" }, I5: { score: "1-2" }, I6: { score: "2-0" },
      J1: { score: "3-0" }, J2: { score: "2-1" }, J3: { score: "2-0" },
      J4: { score: "0-1" }, J5: { outcome: "2", score: "1-0" }, J6: { score: "0-3" },
      K1: { score: "2-0" }, K2: { score: "0-2" }, K3: { score: "2-1" },
      K4: { score: "1-0" }, K5: { score: "0-1" }, K6: { score: "2-0" },
      L1: { score: "2-0" }, L2: { score: "2-1" }, L3: { score: "1-0" },
      L4: { score: "0-2" }, L5: { score: "0-2" }, L6: { score: "2-1" },
    },
    groups: {
      A: ["Sydkorea", "Mexiko", "Tjeckien", "Sydafrika"],
      B: ["Schweiz", "Kanada", "Bosnien&Her", "Qatar"],
      C: ["USA", "Australien", "Turkiet", "Paraguay"],
      D: ["Brasilien", "Marocko", "Skottland", "Haiti"],
      E: ["Tyskland", "Ecuador", "Elfenbenskusten", "Curaçao"],
      F: ["Nederländerna", "Sverige", "Tunisien", "Japan"],
      G: ["Spanien", "Uruguay", "Kap Verde", "Saudiarabien"],
      H: ["Belgien", "Egypten", "Nya Zeeland", "Iran"],
      I: ["Frankrike", "Norge", "Senegal", "Irak"],
      J: ["Argentina", "Algeriet", "Österrike", "Jordanien"],
      K: ["Portugal", "Colombia", "DR Kongo", "Uzbekistan"],
      L: ["England", "Kroatien", "Ghana", "Panama"],
    },
  },
  {
    id: "empa",
    name: "Empa",
    avatar: "🦈",
    special: {
      winner: "Portugal",
      top4: ["Spanien", "Frankrike", "England"],
      goldenBoot: "Harry Kane",
      mostAssists: "Ousmane Dembele",
      mostGoalsCountry: "Spanien",
      bestKeeper: "Unai Simón",
      firstGoal: "Sydafrika",
    },
    matches: {
      A1: { score: "2-1" }, A2: { score: "2-2" }, A3: { score: "1-1" },
      A4: { score: "2-2" }, A5: { score: "0-1" }, A6: { score: "1-2" },
      B1: { score: "2-0" }, B2: { score: "0-3" }, B3: { score: "2-1" },
      B4: { score: "2-0" }, B5: { score: "2-2" }, B6: { score: "1-0" },
      C1: { score: "2-1" }, C2: { score: "1-3" }, C3: { score: "1-0" },
      C4: { score: "2-0" }, C5: { score: "2-0" }, C6: { score: "0-0" },
      D1: { score: "3-1" }, D2: { score: "0-2" }, D3: { score: "1-1" },
      D4: { score: "4-0" }, D5: { score: "3-0" }, D6: { score: "0-2" },
      E1: { score: "4-0" }, E2: { score: "1-1" }, E3: { score: "4-1" },
      E4: { score: "3-0" }, E5: { score: "0-2" }, E6: { score: "1-3" },
      F1: { score: "3-1" }, F2: { score: "2-1" }, F3: { score: "2-2" },
      F4: { score: "0-3" }, F5: { score: "0-3" }, F6: { score: "2-3" },
      G1: { score: "5-1" }, G2: { score: "0-3" }, G3: { score: "5-0" },
      G4: { score: "2-0" }, G5: { score: "0-0" }, G6: { score: "0-3" },
      H1: { score: "3-1" }, H2: { score: "1-0" }, H3: { score: "3-0" },
      H4: { score: "1-3" }, H5: { score: "0-2" }, H6: { score: "2-0" },
      I1: { score: "4-0" }, I2: { score: "0-3" }, I3: { score: "5-0" },
      I4: { score: "2-0" }, I5: { score: "1-3" }, I6: { score: "2-0" },
      J1: { score: "3-0" }, J2: { score: "2-0" }, J3: { score: "3-1" },
      J4: { score: "0-1" }, J5: { score: "0-1" }, J6: { score: "0-2" },
      K1: { score: "4-1" }, K2: { score: "0-3" }, K3: { score: "3-0" },
      K4: { score: "1-1" }, K5: { score: "1-2" }, K6: { score: "1-1" },
      L1: { score: "3-1" }, L2: { score: "1-1" }, L3: { score: "3-0" },
      L4: { score: "0-3" }, L5: { score: "1-4" }, L6: { score: "2-0" },
    },
    groups: {
      A: ["Mexiko", "Sydkorea", "Tjeckien", "Sydafrika"],
      B: ["Schweiz", "Kanada", "Bosnien&Her", "Qatar"],
      C: ["Turkiet", "USA", "Paraguay", "Australien"],
      D: ["Brasilien", "Skottland", "Marocko", "Haiti"],
      E: ["Tyskland", "Ecuador", "Elfenbenskusten", "Curaçao"],
      F: ["Nederländerna", "Sverige", "Japan", "Tunisien"],
      G: ["Spanien", "Uruguay", "Saudiarabien", "Kap Verde"],
      H: ["Belgien", "Egypten", "Iran", "Nya Zeeland"],
      I: ["Frankrike", "Norge", "Senegal", "Irak"],
      J: ["Argentina", "Österrike", "Algeriet", "Jordanien"],
      K: ["Portugal", "Colombia", "DR Kongo", "Uzbekistan"],
      L: ["England", "Kroatien", "Ghana", "Panama"],
    },
  },
  {
    id: "stefan",
    name: "Stefan",
    avatar: "🐂",
    special: {
      winner: "Spanien",
      top4: ["Frankrike", "England", "Portugal"],
      goldenBoot: "Igor Thiago",
      mostAssists: "Pedri Gonzalez",
      mostGoalsCountry: "Brasilien",
      bestKeeper: "Unai Simón",
      firstGoal: "Mexico",
    },
    matches: {
      A1: { score: "1-0" }, A2: { score: "1-1" }, A3: { score: "2-1" },
      A4: { score: "2-1" }, A5: { score: "0-2" }, A6: { score: "0-1" },
      B1: { score: "0-0" }, B2: { score: "0-3" }, B3: { score: "2-0" },
      B4: { score: "2-0" }, B5: { score: "1-0" }, B6: { score: "2-0" },
      C1: { score: "2-1" }, C2: { score: "0-2" }, C3: { score: "1-0" },
      C4: { score: "2-0" }, C5: { score: "1-0" }, C6: { score: "1-0" },
      D1: { score: "2-0" }, D2: { score: "0-3" }, D3: { score: "0-1" },
      D4: { score: "9-0" }, D5: { score: "3-0" }, D6: { score: "0-2" },
      E1: { score: "6-0" }, E2: { score: "0-1" }, E3: { score: "3-0" },
      E4: { score: "3-0" }, E5: { score: "0-2" }, E6: { score: "0-0" },
      F1: { score: "2-2" }, F2: { score: "2-0" }, F3: { score: "2-1" },
      F4: { score: "0-2" }, F5: { score: "0-3" }, F6: { score: "2-2" },
      G1: { score: "7-0" }, G2: { score: "0-3" }, G3: { score: "5-0" },
      G4: { score: "4-0" }, G5: { score: "0-2" }, G6: { score: "1-2" },
      H1: { score: "2-1" }, H2: { score: "2-1" }, H3: { score: "2-0" },
      H4: { score: "0-2" }, H5: { score: "0-3" }, H6: { score: "1-0" },
      I1: { score: "3-0" }, I2: { score: "0-3" }, I3: { score: "5-0" },
      I4: { score: "2-1" }, I5: { score: "1-2" }, I6: { score: "1-0" },
      J1: { score: "3-1" }, J2: { score: "3-1" }, J3: { score: "2-0" },
      J4: { score: "0-3" }, J5: { score: "0-1" }, J6: { score: "0-4" },
      K1: { score: "4-0" }, K2: { score: "0-2" }, K3: { score: "6-0" },
      K4: { score: "2-0" }, K5: { score: "0-2" }, K6: { score: "1-1" },
      L1: { score: "2-1" }, L2: { score: "2-2" }, L3: { score: "3-0" },
      L4: { score: "0-2" }, L5: { score: "0-3" }, L6: { score: "1-0" },
    },
    groups: {
      A: ["Mexiko", "Sydkorea", "Tjeckien", "Sydafrika"],
      B: ["Schweiz", "Kanada", "Bosnien&Her", "Qatar"],
      C: ["Turkiet", "USA", "Paraguay", "Australien"],
      D: ["Brasilien", "Marocko", "Skottland", "Haiti"],
      E: ["Tyskland", "Ecuador", "Elfenbenskusten", "Curaçao"],
      F: ["Nederländerna", "Japan", "Sverige", "Tunisien"],
      G: ["Spanien", "Uruguay", "Saudiarabien", "Kap Verde"],
      H: ["Belgien", "Egypten", "Iran", "Nya Zeeland"],
      I: ["Frankrike", "Norge", "Senegal", "Irak"],
      J: ["Argentina", "Österrike", "Algeriet", "Jordanien"],
      K: ["Portugal", "Colombia", "DR Kongo", "Uzbekistan"],
      L: ["England", "Kroatien", "Ghana", "Panama"],
    },
  },
  {
    id: "rasmus",
    name: "Rasmus",
    avatar: "🦬",
    special: {
      winner: "Frankrike",
      top4: ["Spanien", "Tyskland", "Brasilien"],
      goldenBoot: "Kylian Mbappe",
      mostAssists: "Lamine Yamal",
      mostGoalsCountry: "Frankrike",
      bestKeeper: "Emiliano Martínez",
      firstGoal: "Mexico",
    },
    matches: {
      A1: { score: "3-1" }, A2: { score: "1-2" }, A3: { score: "1-0" },
      A4: { score: "3-1" }, A5: { score: "0-0" }, A6: { outcome: "2", score: "2-1" },
      B1: { score: "1-1" }, B2: { score: "1-0" }, B3: { outcome: "2", score: "3-1" },
      B4: { score: "2-0" }, B5: { score: "0-1" }, B6: { score: "3-1" },
      C1: { score: "2-0" }, C2: { score: "1-2" }, C3: { score: "2-0" },
      C4: { score: "2-1" }, C5: { score: "1-0" }, C6: { score: "0-0" },
      D1: { score: "2-0" }, D2: { score: "0-3" }, D3: { score: "1-1" },
      D4: { score: "3-0" }, D5: { score: "2-0" }, D6: { score: "2-2" },
      E1: { score: "4-1" }, E2: { score: "2-2" }, E3: { score: "3-1" },
      E4: { score: "2-1" }, E5: { score: "0-2" }, E6: { score: "0-1" },
      F1: { score: "1-1" }, F2: { score: "2-1" }, F3: { score: "1-1" },
      F4: { score: "2-1" }, F5: { score: "1-3" }, F6: { score: "1-2" },
      G1: { score: "4-0" }, G2: { score: "0-2" }, G3: { outcome: "1" },
      G4: { score: "2-0" }, G5: { score: "1-1" }, G6: { score: "1-4" },
      H1: { score: "2-1" }, H2: { score: "0-0" }, H3: { outcome: "1" },
      H4: { score: "1-1" }, H5: { score: "0-2" }, H6: { score: "1-0" },
      I1: { score: "4-1" }, I2: { score: "1-1" }, I3: { score: "3-0" },
      I4: { score: "0-1" }, I5: { score: "1-1" }, I6: { score: "2-1" },
      J1: { score: "3-1" }, J2: { score: "1-1" }, J3: { score: "3-1" },
      J4: { score: "1-1" }, J5: { score: "2-1" }, J6: { score: "0-2" },
      K1: { score: "2-0" }, K2: { score: "0-2" }, K3: { score: "2-0" },
      K4: { score: "3-1" }, K5: { score: "1-1" }, K6: { score: "2-0" },
      L1: { score: "1-2" }, L2: { score: "2-2" }, L3: { score: "2-1" },
      L4: { score: "1-2" }, L5: { score: "2-2" }, L6: { score: "2-0" },
    },
    groups: {
      A: ["Mexiko", "Sydkorea", "Sydafrika", "Tjeckien"],
      B: ["Bosnien&Her", "Kanada", "Schweiz", "Qatar"],
      C: ["Turkiet", "USA", "Paraguay", "Australien"],
      D: ["Brasilien", "Skottland", "Marocko", "Haiti"],
      E: ["Tyskland", "Ecuador", "Elfenbenskusten", "Curaçao"],
      F: ["Nederländerna", "Sverige", "Japan", "Tunisien"],
      G: ["Spanien", "Uruguay", "Saudiarabien", "Kap Verde"],
      H: ["Belgien", "Egypten", "Nya Zeeland", "Iran"],
      I: ["Frankrike", "Senegal", "Norge", "Irak"],
      J: ["Argentina", "Algeriet", "Jordanien", "Österrike"],
      K: ["Portugal", "Colombia", "DR Kongo", "Uzbekistan"],
      L: ["Kroatien", "England", "Ghana", "Panama"],
    },
  },
];
